// Point Blank — dummy card content + bot roster.
// NOTE: All card text is placeholder dummy content; will be replaced (AI-generated) later.

window.GAME_DATA = {
  prompts: [
    "My secret talent is ____.",
    "The real reason I was late today: ____.",
    "Honestly, the group chat needs more ____.",
    "My therapist says I should stop ____.",
    "The worst possible theme for a wedding: ____.",
    "I knew the party was over when ____ showed up.",
    "New from IKEA: the ____.",
    "My villain origin story began with ____.",
    "Rejected ice cream flavor: ____.",
    "Step 1: ____. Step 2: profit.",
    "The museum's newest exhibit: ____.",
    "What's that smell? Oh, it's ____."
  ],
  answers: [
    "a suspicious amount of glitter",
    "aggressive interpretive dance",
    "my browser history",
    "an emotional support raccoon",
    "lukewarm soup",
    "the world's smallest violin",
    "a 45-minute voicemail",
    "unsolicited life advice",
    "decorative gourds",
    "a PowerPoint about my feelings",
    "extreme couponing",
    "one single crouton",
    "a haunted Roomba",
    "matching family pajamas",
    "the office printer",
    "an unskippable ad",
    "competitive napping",
    "my lawyer's lawyer",
    "seventeen alarms, all snoozed",
    "a group project",
    "free samples",
    "the neighbor's wifi",
    "a firm handshake",
    "homemade kombucha",
    "an army of pigeons",
    "the last slice of pizza",
    "a motivational poster",
    "karaoke at 2am",
    "my fantasy football team",
    "a very long receipt",
    "soup in a bag",
    "left-handed scissors",
    "a conspiracy corkboard",
    "elevator small talk",
    "expired coupons",
    "interpretive whale sounds"
  ],
  packs: [
    { name: "Classic", cards: 480, free: true },
    { name: "Pop Culture", cards: 260, free: true },
    { name: "Memes & Internet", cards: 320, free: true },
    { name: "Tech & Startups", cards: 180, price: 120 },
    { name: "College Life", cards: 210, price: 140 },
    { name: "Relationships", cards: 190, price: 130 },
    { name: "Office Hours", cards: 150, price: 100 },
    { name: "Pet Owners", cards: 120, price: 90 },
    { name: "Foodies", cards: 140, price: 100 },
    { name: "Travel Disasters", cards: 110, price: 80 },
    { name: "Gym Rats", cards: 90, price: 70 },
    { name: "Parents & Kids", cards: 160, price: 110 },
    { name: "Gamers", cards: 230, price: 150 },
    { name: "Music Festival", cards: 100, price: 80 },
    { name: "Reality TV", cards: 130, price: 90 },
    { name: "Sports Bar", cards: 110, price: 80 },
    { name: "Conspiracy Corner", cards: 95, price: 75 },
    { name: "Awkward Family", cards: 170, price: 110 },
    { name: "Group Chat Energy", cards: 200, price: 130 },
    { name: "Late Night", cards: 140, price: 100 },
    { name: "Retro 2000s", cards: 125, price: 90 },
    { name: "Science Fair", cards: 85, price: 70 },
    { name: "Wedding Season", cards: 105, price: 80 },
    { name: "Roommates", cards: 135, price: 95 },
    { name: "Tax Season", cards: 70, price: 60 },
    { name: "True Crime", cards: 115, price: 85 }
  ],
  bots: [
    { id: "b1", name: "Priya",  color: "#7C5CFF" },
    { id: "b2", name: "Theo",   color: "#2BC4BE" },
    { id: "b3", name: "Zoe",    color: "#FF4D8D" },
    { id: "b4", name: "Marcus", color: "#5CA9FF" }
  ],
  chatLines: [
    { who: "b1", text: "yooo we're in" },
    { who: "b2", text: "I have been training for this" },
    { who: "b3", text: "someone is going DOWN tonight" },
    { who: "b4", text: "wait how do I— oh, ready" },
    { who: "b1", text: "start it start it start it" }
  ],
  reactions: ["😂", "💀", "🔥", "👏"]
};
